spring:
  application:
    name: checklist manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daw_database?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

server:
  port: 8080


