spring:
  application:
    name: checklist manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daw_database?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  jpa:
    hibernate:
     ddl-auto: update

    show-sql: true

    database: postgresql

    properties:
     hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
       use_jdbc_metadata_defaults: false

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 8080


