spring:
  application:
    name: checklist manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://google/daw_database?useSSL=false&socketFactoryArg=prj-1718-2-li61d-g1:europe-west2:daw-database&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    hibernate:
     ddl-auto: update

    show-sql: true

    database: postgresql

    properties:
     hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
       use_jdbc_metadata_defaults: false

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: true
  resources:
      add-mappings: true

server:
  port: 9000


